### ISSUE TITLE
Is there any function to find the points between a route using geofirestore?

### ISSUE THREAD

**Issue by MuruganDurai** [geofirestore/geofirestore-js#100]
I want to find potholes of the road for the given route (starting & ending lat/long points). All the potholes are stored at google-cloud-firestore as it is required by geofirestore.

**Comment by MichaelSolati** [comment]
Do the answer would be no. It's only designed to query coordinates/points. What you would likely want to do is map a slew of coordinates along your path and make the query radius equal to half the distance between the points (assuming they're equidistant) then do some additional filtering on your side.
