### ISSUE TITLE
 Problem With Query

### ISSUE THREAD

**Issue by VesperDev** [geofirestore/geofirestore-js#102]
Hello my friends, i have a  doubt

Have a code for get the result in my collection, but ever ever i have empty data, i write radius 0 and i have 2 results ¿why?

"geofirestore": "^3.0.2"

        let db = firebase.firestore()
        const geoFirestore: GeoFirestore = new GeoFirestore(db)

        geoFirestore.collection('talleres')
            .near({ center: new firebase.firestore.GeoPoint(latitude, longitude), radius: 30 })
            .onSnapshot((snapshot) => {
                console.log(snapshot)
        })

![Captura de Pantalla 2019-04-26 a la(s) 0 49 38](https://user-images.githubusercontent.com/14016458/56786064-32300b00-67bd-11e9-84c1-41d94fea7e0e.png)

![Captura de Pantalla 2019-04-26 a la(s) 0 58 55](https://user-images.githubusercontent.com/14016458/56786417-81c30680-67be-11e9-965a-b82e1129e3c4.png)

**Comment by MichaelSolati** [comment]
@VesperDev I'm sorry I'm having difficulty understanding your question. Could you elaborate, or maybe share an example (like on [stackblitz](https://stackblitz.com))

**Comment by VesperDev** [comment]
Yes, of course, basically placing the radius 0 I get results but if I write radio 30 the results do not appear :(

without results
 geoFirestore.collection('talleres')
            .near({ center: new firebase.firestore.GeoPoint(latitude, longitude),radius : 30 })


with results
 geoFirestore.collection('talleres')
            .near({ center: new firebase.firestore.GeoPoint(latitude, longitude),radius : 0 })

**Comment by MichaelSolati** [comment]
Ok, so I finally took a look at it and from what I can gather (just code skimming) before I was doing a check like this...

```JavaScript
if (this._center && this._radius) {
```

If the radius was set to 0 then it was treated as false and there wouldn't be a geoquery. What I'm going to change it is to this:

```JavaScript
if (this._center && typeof this._radius !== 'undefined') {
```

Which should pass if 0 is inputted and give a geoquery of a 0 radius.

**Comment by VesperDev** [comment]
Thanks my friends let my check

**Comment by MichaelSolati** [comment]
You should be able to run `npm i geofirestore/geofirestore-js#dev` to test it.

**Comment by MichaelSolati** [comment]
Geofirestore version 3.3.1 is going through CI and will be autodeployed to NPM. That should take care of this issue. Enjoy!

**Comment by michelemangiacotti** [comment]
I've the same problem, any solution?

**Comment by MichaelSolati** [comment]
@michelemangiacotti what version are you using?

**Comment by michelemangiacotti** [comment]
My version is ;     "geofirestore": "^3.3.1".

**Comment by MichaelSolati** [comment]
Ok, so I've created a somewhat simple example that works here => https://stackblitz.com/edit/typescript-sa8wdv

Line 50 is the query and the snapshot, and the structure of the docs looks like this:

![Screen Shot 2019-07-29 at 3 34 27 PM](https://user-images.githubusercontent.com/11811422/62087381-60871180-b216-11e9-8d80-052f515b4a41.png)

If it's not working and your code looks like the stackblitz, it's likely a data structure issue.

**Comment by michelemangiacotti** [comment]
Hi, thank for the quickly response, I've try your solution but it don't work for me.
I've this firestore data structure : 
![immagine](https://user-images.githubusercontent.com/44534678/62155563-7f1a0500-b309-11e9-8e52-9b38666bcf61.png)
I would like load from my table "items" only elements that are into a range of my approximate position.
My code is very similar from your, I add too your solution, 
![immagine](https://user-images.githubusercontent.com/44534678/62156085-93123680-b30a-11e9-8e73-3c3cf8378e19.png)

I don't understand if there is a misunderstanding, because you make the call near on a list already loaded from the database, could you tell me if I'm wrong approach?

**Comment by MichaelSolati** [comment]
Ah, that second near is the actually query, the first one is just to populate the database incase there are less than 10 documents. But looking at your data structure, is see the `l` field is embedded in the address when it needs to be in the root of the document. I also don't see a `g` field which is also necessary. Please review the required data structure for `geofirestore` [here](https://github.com/geofirestore/geofirestore-js/tree/v3.3.1#data-structure).

**Comment by michelemangiacotti** [comment]
Ah, now I understand, thank you, one last question: the structure of my "items" must be composed of only the 3 fields:
 g: string;
 l: GeoPoint;
 d: DocumentData;
or can I have additional fields as I showed you in the previous answer?

**Comment by MichaelSolati** [comment]
@michelemangiacotti well the idea is that at the top level `geofirestore` uses the data and everything in the `d` level is your data. While you can have things on the top level, it'll get funky and is not recommended.

**Comment by michelemangiacotti** [comment]
Hello Michael, I tried to play a simple example with your proposed fire structure and I have a strange behavior, the elements are loaded only when the radian is above 4000, my elements are all 20-30 meters from my current location, and especially are loaded by the query always all elements, I tried to insert an element very far away as position but is loaded the same by the query.
This is my structure, the call is the one you sent me a while ago.
Would you know how to help me?

![image](https://user-images.githubusercontent.com/44534678/63250204-6008f600-c26b-11e9-981f-d0322cefc15a.png)

**Comment by MichaelSolati** [comment]
@michelemangiacotti your `g` field only has a degree of precision of 3, so your `g` field (the geohash), ideally you'd want to go to 10 degrees of precision (otherwise it'll be very far from the origin). Also that geohash is not a valid geohash... You'd expect `srb0bzyd6p` for those coordinates...

**Comment by michelemangiacotti** [comment]
I'm sorry Michele this thing had escaped me, at this point I can ask you how to generate a geohash for coordinates, I'm doing tests on records built by hand by me, could you tell me what I have to call to generate a test structure that has a valid geohash based on coordinates?
Thanks for the quick answer!

**Comment by MichaelSolati** [comment]
@michelemangiacotti I have a library called geokit which you can pass in a LatLng literal in order to create a geohash => https://www.npmjs.com/package/geokit#geokithashcoordinates-latlngliteral-precision-number-string

Or you could just use geofirestore and add documents with it.

**Comment by michelemangiacotti** [comment]
Thank you @MichaelSolati your are a boss, it work!

**Comment by michelemangiacotti** [comment]
Hello Michael, I would like to know if you can add a condition where to the call: 

geofirestore.collection('items').where("d.myField", "==", true).near({
        center: new firebase.firestore.GeoPoint(latitude, longitude),
        radius: 10,
      })

**Comment by MichaelSolati** [comment]
See #137

**Comment by hindsricardo** [comment]
Looks like the issue is still persisting. v3.3.1 only works when the radius is set to 0

**Comment by MichaelSolati** [comment]
@hindsricardo can you explain your issue in more detail?

**Comment by hindsricardo** [comment]
@MichaelSolati v3.3.1 only works when the radius is set to 0

Here is my code is firebase cloud functions:

const {GeoFirestore} = require('geofirestore');

const database = admin.firestore();
const geofirestore = new GeoFirestore(database);
const Geo = geofirestore.collection('profile');

exports.initialLocationSearch = functions.https.onRequest((req, res) => {
  let body = req.body;
  let parseBody = JSON.parse(body);

  // Create a GeoQuery based on a location
  console.log(body, parseBody.radius, parseBody.lat, parseBody.long)

  const query =  Geo.near({ center: new admin.firestore.GeoPoint(parseBody.lat, parseBody.long), radius: parseBody.radius }).limit(100);

  query.get().then((value) => {
    res.status(200).send(value._docs.map((x) => {
      x._data = x.data();
      return x;
    }));
  });

})

I checked the library code and it looks like the fixed you mentioned below is actually in place. 

if (this._center && typeof this._radius !== 'undefined') {


Any suggestions. This is the last feature preventing me from finishing my app.

**Comment by MichaelSolati** [comment]
`_docs` isn't a valid attribute or property of a geosnapshot, just use `docs` also can you provide a stackblitz example? Without access to the database I couldn't test this. 

Another possible issue is that the database structure is invalid. A screenshot from the firebase console could be helpful. 

Here's an app example with a query and radius which does work => https://stackblitz.com/edit/geofirestore-distance
