### ISSUE TITLE
How to query firestore collection when GeoFirestore is used ?

### ISSUE THREAD

**Issue by patpune** [geofirestore/geofirestore-js#103]
As I play with  GeoFirestore (which is very cool), the data structure that it creates in firestore is like

(collection-name)

    |-"geohash1" 

         |- d: {"my data" dictionary} 

         |- g: "geohash" 

         |- l: geopoint:location 

    |-"geohash2" 

           |- d: {"my data" dictionary} 

           |- g: "geohash" 

           |- l: geopoint:location` 

Using the above I am able to locate the places and associate the data. So the library is doing it's job and doing it well.
The challenge I have been facing with this is that , in my other panels (non map related) I am also suppose to query name:value pairs associated with "my data" which is now stored as a map. So my question is:
- How do I query "my data" which is now stored under a map ?
OR 
- can the geofirestore help store the data in the below format which will allow me to query "my data" as well as allow geofirestore to help with the geo mapping ?
<collection-name>

    |-"geohash1" 

        |- "my_data_key1" : "my_data_value1" 

        |- "my_data_key2" : "my_data_value2" 

        |- "my_data_keyn" : "my_data_valuen" 

        |- g: "geohash" 

        |- l: geopoint:location 

    |-"geohash2" 

        |- "my_data_key1" : "my_data_value1" 

        |- "my_data_key2" : "my_data_value2" 

        |- "my_data_keyn" : "my_data_valuen" 

        |- g: "geohash" 

        |- l: geopoint:location 

    .
Insights ?

**Comment by MichaelSolati** [comment]
So, no, currently `geofirestore` CAN'T do this... However I started working on version 4 which will... However v4 may not be compatible with v3 (that's yet to be seen, and if that is the case I will write a conversion script for people).

**Comment by patpune** [comment]
@MichaelSolati - Thanks for your response.  So then if one needs to query  "mydata" will one need to denormalize the "mydata" and keep two copies (in sync) ? When searching by geohash use one collection and when need to query mydata use another one ?

**Comment by AlcuinGuest** [comment]
@patpune We do this, and decided to create 2 collections. One with geofirestore data (and nothing else), and one with the full documents. The documents are linked by the same ID.

**Comment by jerryheir** [comment]
I predict a lot of people will be using this soon. But I also noticed there is no way to do a .where() on the query, the data is not really accessible @MichaelSolati

**Comment by MichaelSolati** [comment]
@jerryheir I'm not sure what you mean when you say you can't use the `.where()`

**Comment by jerryheir** [comment]
Thanks for your quick response @MichaelSolati , I created a small issue for it
