### ISSUE TITLE
Geofirestore Instantiation

### ISSUE THREAD

**Issue by stot3** [geofirestore/geofirestore-js#106]
After futher investigation Geofirestore is unable to be instantiated with firestore. I have this error in console. I am using firestore@3.3.0 on Angular 7.2.4. 

ERROR in src/app/tools/tools.service.ts(1011,51): error TS2345: Argument of type 'typeof firestore' is not assignable to parameter of type 'FirebaseFirestore | Firestore'.
  Type 'typeof firestore' is not assignable to type 'Firestore'.
    Property 'settings' is missing in type 'typeof firestore', here it is being used in the code. 

import {firestore} from 'firebase/app'; 
            
const geoFire: any = new GeoFirestore(firestore)

even when I use const geoFire = new Geofirestore(firestore.Firestore) it does not work. I'm just gonna roll back. 

I went back to see which version this particularly comes up on, my code is compatiable with version 3.1.0, but anything past that it does not work.

**Comment by MichaelSolati** [comment]
Duplicate of #58, please check my answer there
