### ISSUE TITLE
If passing radius to geofirestore.collection, getting empty docs in response.

### ISSUE THREAD

**Issue by prashantkumarjha47** [geofirestore/geofirestore-js#107]
If passing radius to geofirestore.collection, getting empty docs in response whereas if passing radius 0 getting all
`this.geofirestore = new GeoFirestore(this.firestore)       
this.query = this.geofirestore.collection("PassengerLocationDb").near({ center: new 
       firebase.firestore.GeoPoint(35.17506145581017, 129.08302834244256), radius: 5 })
        this.query.onSnapshot((docs) => {
            docs.forEach(doc => {
                console.log(doc.data());
            })
        }) `
![Screenshot 2019-05-16 at 2 32 00 PM](https://user-images.githubusercontent.com/37287172/57841059-7b391500-77e7-11e9-9cd3-4ca3c0a1d91f.png)

**Comment by MichaelSolati** [comment]
Data and documents near to be structured in a special way in order to make queries. I'd recommend reading the thread in issue #81 to understand, but keeping it simple docs need to be created by geofirestore in order to be queried by geofirestore.
