### ISSUE TITLE
Query returns no documents in React Native

### ISSUE THREAD

**Issue by chrisjaimesdev** [geofirestore/geofirestore-js#108]
I have the following code in a react native project

     import firebase from 'firebase';
     import { GeoFirestore } from "geofirestore";

                               .
                               .
                               .

     var geofirestoreRef = new GeoFirestore(firebase.firestore());

     const geocollection = geofirestoreRef.collection('users');

      geocollection.near({
        center: new firebase.firestore.GeoPoint(37.33233141, -122.0312186),
        radius: 1000
      }).get().then((geousers) => {
        console.log("users in area ob: ", geousers.docs);
      }).catch(() => {
        console.log("error when querying users with geolocation");
      });

Also I have 3 documents in my `users` collection with the following field

<img width="385" alt="Screen Shot 2019-05-17 at 11 51 48 PM" src="https://user-images.githubusercontent.com/22719516/57964189-12dd5700-78ff-11e9-9f29-f9b95f20291f.png">

however every time I run it, I am getting an empty snapshot with no users in the `then()` block. Am I missing something here?

**Comment by chrisjaimesdev** [comment]
ok I just realized I most have the following structure for the geolocation data
<img width="249" alt="Screen Shot 2019-05-18 at 12 16 34 AM" src="https://user-images.githubusercontent.com/22719516/57964352-3950c180-7902-11e9-93c4-d8cad74597ea.png">

however i can't find any example out there explaining how to insert with Geofirestore :S

**Comment by chrisjaimesdev** [comment]
ok just realized I have to use Geofirestore to insert the doc so that the obj has the proper structure ;)

**Comment by MichaelSolati** [comment]
@chrisjaimesdev this is something I'm working on, a bit of a change in how I "index" data so it's easier for people new to geofirestore to use. But that will probably be out next month...

**Comment by chrisjaimesdev** [comment]
@MichaelSolati awesome! can't wait for newer versions :) thank you!
