### ISSUE TITLE
Distance is broken when it is a query with listener

### ISSUE THREAD

**Issue by JorgeMoralesLopez** [geofirestore/geofirestore-js#127]
I am using this wonderful library and it works very well but I am having a problem, the distance is broken when a query is made with listener event. It actually breaks when a new element is created, user, point ... However if it is with get in eve of onSnapShot it works without problems.

```JavaScript
const firestore = firebase.firestore();
const geofirestore = new GeoFirestore(firestore);
const geocollection = geofirestore.collection('users').where('active', '==', true);

try {
    let usersQuery = geocollection.limit(30 + plusLimit).near({
         center: new firebase.firestore.GeoPoint(lat, lng),
         radius: radius
   })

   let docQuery = await usersQuery.onSnapshot((querySnapshot) => {
      let users = [];
      for (let i = 0; i < querySnapshot.docs.length; i++) { 
           //here is the distance problem that if I do it with get, it works but with onSnapShot no
           let user = {...querySnapshot.docs[i].data(), distance = querySnapshot.docChanges()[i].doc.distance, id: querySnapshot.docs[i].id}
          users.push(user)
      }
   }

} catch (error) {
  console.log(error)
} 
```

**Comment by MichaelSolati** [comment]
Quick question, is `distance = querySnapshot.docChanges()[i].doc.distance` a typo?

**Comment by JorgeMoralesLopez** [comment]
No, it's not a typo, it works perfect when it's get instead of onSnapshot, in this example I put it in another way in case it looks clearer.
`
let docQuery = await usersQuery.onSnapshot((querySnapshot) => {
      let users = [];
      for (let i = 0; i < querySnapshot.docs.length; i++) { 
           //here is the distance problem that if I do it with get, it works but with onSnapShot no
           let {doc} = querySnapshot.docChanges()[i];
           let distance = doc.distance
           let user = {...querySnapshot.docs[i].data(), distance = distance, id: querySnapshot.docs[i].id}
          users.push(user)
      }
   }

`

**Comment by MichaelSolati** [comment]
Got it, ok, I'll try and replicate and go from there. But I think my confusion is that in an object you're using a `=` instead of a `:`. Still I'll dig into this over the week. I need to get on some bug fixes anyway 😅

**Comment by JorgeMoralesLopez** [comment]
Oh, yes ... Sorry for my mistake is: instead of =
let user = {... querySnapshot.docs [i] .data (), distance: distance, id: querySnapshot.docs [i] .id}
Thanks @Solati

**Comment by JorgeMoralesLopez** [comment]
Hello @MichaelSolati, I have detected a problem similar to the one I mentioned before. In a document, d: {element: id: {isVisible: true}} when it has this deep nesting inside, when you use onSnapshot for listening, if I want to access isVisible element [id] .isVisible, it returns the result, without However, if I am in that context when the document is modified in real time, it returns undefined, that is, element [id] .isVisible === undefined, however element [id] === defined. Why do not you reach the other level?
I use it to show a button or not and it is a screen that works in real time.
The truth is that I do not know if it is a problem of mine, of firebase, or geofirestore.
Thank you!

**Comment by MichaelSolati** [comment]
@JorgeMoralesLopez could you make a gist example of what that snapshot function looks like? The closer I can get to replicating your code the better 😅

**Comment by JorgeMoralesLopez** [comment]
I solved it with a forEach, before I used a for loop and with...
let {doc} = querySnapshot.docChanges () [i];
let distance = doc.distance;
The application broke, however with the forEach it works wonders.
Thanks @MichaelSolati

**Comment by MichaelSolati** [comment]
That's still odd, but likely some weirdness with you iterating over a function you may have kept calling. I'll close this for now, but if you have more related/similar issues please post back with specific code examples (so I can better understand what you're doing).
