### ISSUE TITLE
Results only returned from one side of the Prime Meridian

### ISSUE THREAD

**Issue by palkerecsenyi** [geofirestore/geofirestore-js#132]
I have a `places` collection containing some places (inserted by GeoFirestore), all of which are to the East of the Prime Meridian.

If I run the following query (setting the centre point to be to the East of the Prime Meridian), all of the places are returned: 
```js
geofirestore.collection('places')
    .near({
        center: new firebase.firestore.GeoPoint(12.345, 0.1),
        radius: 100000
    })
    .get()
```

However, when I run the following query (setting the centre point to be to the West of the Prime Meridian), no places are returned, even though they are all within the radius:

```js
geofirestore.collection('places')
    .near({
        center: new firebase.firestore.GeoPoint(12.345, -0.1),
        radius: 100000
    })
    .get()
```

I haven't tried doing this with latitude (North/South of the equator), but a similar issue perhaps might exist for latitude too.

**Comment by willbattel** [comment]
Likely due to fundamental limitations of geohashing. https://en.wikipedia.org/wiki/Geohash#Limitations_when_used_for_deciding_proximity

This library would need to do queries on both sides of the 180 degree meridian.

**Comment by palkerecsenyi** [comment]
That makes sense @willbattel. Could this be implemented into GeoFirestore so that (maybe by adding an additional option to `.near`) it queries both sides of the meridian automatically?

**Comment by hindsricardo** [comment]
Was this resolved? This kind of makes the library unusable

**Comment by MichaelSolati** [comment]
@hindsricardo There won't be a fix for this as it is a fundamental limitations of geohashing, and there is no neat way to implement a fix for this. (Unless someone wants to propose and implement a fix)
