### ISSUE TITLE
making compound queries using geofirestore

### ISSUE THREAD

**Issue by shekhars-realm** [geofirestore/geofirestore-js#135]
I am trying to make something like this: 

geofirestore.collection('locations')
    .near({
      center: new admin.firestore.GeoPoint(req.body.location.lat, req.body.location.lng),
      radius: req.body.radius
    })
    .where('tags', 'array-contains', req.body.searchText)
    .orderBy('startTime', 'desc')

Error: 
geofirestore.collection(...).near(...).where(...).orderBy is not a function

**Comment by MichaelSolati** [comment]
Queries with `orderBy` are not supported by this library, please take a look at the [README for more details](https://github.com/geofirestore/geofirestore-js/tree/v3.3.1#limitations--considerations).
