### ISSUE TITLE
Support GeoJSON Point as location data source

### ISSUE THREAD

**Issue by misovan** [geofirestore/geofirestore-js#138]
My source data need to be formatted as [GeoJSON Feature objects](https://tools.ietf.org/html/rfc7946#section-3.2), where location data is stored as [GeoJSON Points](https://tools.ietf.org/html/rfc7946#section-3.1.2), e.g.:
```
{
      "type": "Feature",
      "properties": {
        "scalerank": 2,
        "name": "Niagara Falls",
        "comment": null,
        "name_alt": null,
        "region": "North America",
        "subregion": null,
        "featureclass": "waterfall"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [-79.04411780507252, 43.08771393436908]
      }
}
```
Would it be meaningful to accept GeoJSON Point as a location data source when adding new GeoDocument, e.g.:

```
// Add a GeoDocument to a GeoCollection
geocollection.add({
  name: 'Geofirestore',
  score: 100,
  // Location coordinates must be a Firebase GeoPoint or a GeoJSON Point!
  geometry:{
      type:'Point'
      coordinates: [-73.9851, 40.7589]
})
```
Another option could be to accept [lng, lat] array:

```
geocollection.add({
  name: 'Geofirestore',
  score: 100,
  // Location coordinates must be a Firebase GeoPoint or [lng, lat] array!
  geometry:{
      type:'Point'
      coordinates: [-73.9851, 40.7589]
},
'geometry.coordinates'
)
```

**Comment by MichaelSolati** [comment]
So as the plugin stands now (v3) I don't think I'd support that. I had initially created the plugin adamant to use GeoPoints, because if Google does choose to support geoqueries natively it would likely be through this data structure. However I'd be open to it in the future. (I'll leave this open for now as I consider how to address/do this)
