### ISSUE TITLE
Could not use .near and .where together in a query 

### ISSUE THREAD

**Issue by tailaw** [geofirestore/geofirestore-js#140]
I have spent the a good few hours trying to figure out why I couldn't have .near and .where to work together, the error message I get is 

`[Unhandled promise rejection: FirebaseError: Invalid query. You have a where filter with an inequality (<, <=, >, or >=) on field 'd.endTime' and so you must also use 'd.endTime' as your first Query.orderBy(), but your first Query.orderBy() is on field 'g' instead.]`

I have the following code 
```
const geofirestore = new GeoFirestore(firebase.firestore());
const geocollection = geofirestore.collection('Events');

geocollection
        .near({ center: new firebase.firestore.GeoPoint(coordinate.latitude, coordinate.longitude), radius: 15 })
        .where("endTime", ">=", now)
        .get()
```

I am using geofirestore version 3.3.1. I am not using an orderBy() in my code so apparently orderBy is being used inside .get() or .near(), is there any option to specific the key for the orderBy inside these functions?

**Comment by MichaelSolati** [comment]
While the readme discusses the intability to do startat and what not, effectively you [cannot do any compound ranges on more than one field](https://firebase.google.com/docs/firestore/query-data/queries#compound_queries). Startat and other methods are basically the same as inequality filters, so it wouldn't work.

**Comment by BadMask121** [comment]
im having this same issue, im trying aggregation query on the `d` field but i get this error `Error: firebase.firestore().collection().orderBy() Invalid query. You have a where filter with an inequality (<, <=, >, or >=) on field 'd.data' and so you must also use 'd.data' as your first Query.orderBy(), but your first Query.orderBy() is on field 'g' instead`
