### ISSUE TITLE
Issue with Query when 'where' is used

### ISSUE THREAD

**Issue by MarkedWarrior** [geofirestore/geofirestore-js#142]
Hey, thanks for an awesome library! I'm using Firebase Functions and testing it out the query on one of my Firestore triggers. it works great when I'm doing a simple 'near' query but as soon as I add a 'where' it returns 0. Below is a screenshot of my db and code. Any advice would be helpful.
<img width="1021" alt="Screen Shot 2019-10-05 at 2 32 22 PM" src="https://user-images.githubusercontent.com/15189068/66259739-e1b4d480-e782-11e9-8d31-8f37ee917c61.png">

<img width="563" alt="Screen Shot 2019-10-05 at 2 31 43 PM" src="https://user-images.githubusercontent.com/15189068/66259741-e5e0f200-e782-11e9-97d4-60381dbf9315.png">

**Comment by MichaelSolati** [comment]
Have you indexed your database? The query may be failing because it's not queried... Once you execute `get()` on the query you should do a `catch` to see if it gives you a url to index your database.

If you're doing an `onSnapshot` instead of `get` the second callback would be your error handler.

**Comment by MarkedWarrior** [comment]
@MichaelSolati Yeah my db is index. I am doing a get. I've attached more screenshots that can clarify things. Thank you for your prompt response!

<img width="860" alt="Screen Shot 2019-10-05 at 8 42 14 PM" src="https://user-images.githubusercontent.com/15189068/66262556-c52f9100-e7b0-11e9-8107-81382a82c16d.png">
<img width="600" alt="Screen Shot 2019-10-05 at 8 42 00 PM" src="https://user-images.githubusercontent.com/15189068/66262557-c82a8180-e7b0-11e9-886c-6fa1cd378ffd.png">

**Comment by MichaelSolati** [comment]
Ok, so I missed something obvious when looking over your screenshots (my bad). Data queried by geofirestore needs to be maintained by geofirestore, and geofirestore stores all data associated with your object inside the `d` property, not at the top level. It's an inconvenience, but a necessity at this time.

I do plan on changing how geofirestore works, but time constraints have prevented me from working on v4.0.0.

**Comment by MarkedWarrior** [comment]
Ah okay gotcha! Any chance you might know when v4.0.0 will be out? :)

**Comment by barakoles** [comment]
@MarkedWarrior Did you make this work?

**Comment by MarkedWarrior** [comment]
@barakoles yeah I just restructured my data to be included under d and everything worked correctly

**Comment by barakoles** [comment]
@MarkedWarrior Awesome, you used the same query and had to index the db as well right? BTW, what is this 'formater' you use that highlights the parameters you should use? thanks dude

**Comment by MarkedWarrior** [comment]
@barakoles Yep, same query! Oh I use Webstorm with typescript installed

**Comment by NickCarducci** [comment]
I have been itching to figure this out and I guess this issue is good place as any to note this for geofirestore users:
````
firebase.initializeApp(firebaseConfig).firestore()
  .collection("planner")
  .where("d.authorId", "in", [`${this.props.auth.uid}`])
````
