### ISSUE TITLE
Is there any way to do pagination on a certain area?

### ISSUE THREAD

**Issue by lsps9150414** [geofirestore/geofirestore-js#144]
I am reading these:
> Internally GeoFirestore creates multiple geohashes around a requested area. It queries them and furter calculations on the seperate results are done within the libary. Because of this the additional filtering methods such as orderBy, startAt and endAt can not be passed though GeoFirestore to Cloud Firestore at this time.

> Limits on geoqueries are applied based on the distance from the center. Geoqueries require an aggregation of queries. When performing a geoquery the library applies the limit on the client.

So in my use case, the user may have potentially thousands of nearby locations to query and I need a way to paginate them. Does the above information mean that it can't be done?

**Comment by MichaelSolati** [comment]
Not really, not in a way that would allow skips. On client side you could allow firestore to cache results and slowly expand the radius of the query. But otherwise I would say not really. This is a limitation of how this sort of hashed and aggregated query works.

**Comment by JorgeMoralesLopez** [comment]
The two methods would be just as expensive because you are asking for more data than you need, first because you repeat data and the other because you ask for more than you initially need ...

**Comment by MichaelSolati** [comment]
My concern wasn't about requesting extra data (which is a cost), I was considering the cost of generating these more unique queries.

**Comment by gauthampait** [comment]
Now that we don't have an available option. I have implemented my search with increasing the radius by 0.15kms. Something I have to live with right now.

I am trying to see if I can read the first set of docs from the cache, and the new paginated data from the server.
