### ISSUE TITLE
What on earth is the radius unit?

### ISSUE THREAD

**Issue by sbilling** [geofirestore/geofirestore-js#147]
Docs claim it is kilometers but ive been seeing some very strange behavior that debunks that as true. 

User A is 45 km from User B.
- query within 10 km: both users returned as within "10"
- query within 5km: neither user returned as within "5"

User A is 10 feet from User C:
- query within 1km: neither user returned as within "1"
- query within 5km: both users returned as within "5"

what am I missing here?

**Comment by MichaelSolati** [comment]
Could I see a project on StackBlitz or glitch that demonstrates this?

**Comment by sbilling** [comment]
So we just let geofirestore handle the locations collection and then users hold a reference to their location doc. So when I say "both users returned" - we are just returning the users that own the associated geo firestore location documents.

**Comment by MichaelSolati** [comment]
So I'm not able to replicate this issue that you're having... 

I created a [StackBlitz](https://stackblitz.com/edit/geofirestore-147) with three users, one user that's set at 0, 0, another user who is about 10 feet away from them, and finally a user that is 45 km away from them. Things seem to work correctly.

I invite you to fork it and create the condition that doesn't work for you. But without a more verbose description/example there doesn't seem to be a bug in the library.
