### ISSUE TITLE
Issue with query onSnapshot while firestore document deleted

### ISSUE THREAD

**Issue by przelu** [geofirestore/geofirestore-js#152]
Hello,
I got a React app with GeoQuery.onSnapshot callback set and 10 docs loaded from Firestore, based on 'near' criteria. One of these docs gets deleted. The callback then reports:
- 1 'removed' change     // this is what I am looking for
- 9 'modified' changes       // this seems weird

My question is about these 'modified' changes being reported, while no changes are done to them. 

Is this expected?   

"react": "^16.10.2",
"geofirestore": "^3.3.1"

**Comment by MichaelSolati** [comment]
Hey @przelu, so I couldn't replicate this issue. Here's a sample I threw together where I make sure there are 5 documents in a firestore database and then remove one item (i update the HTML whenever onSnaphshot is called) => https://stackblitz.com/edit/geofirestore-152

Unfortunately none of the other docs are marked as "modified."

If you could create a stackblitz or glitch that replicates the issue you describe that would be awesome. But is there any chance that the docs might be modified by something else? (I'll keep this open for a week to hear back from you)

**Comment by przelu** [comment]
Hi @MichaelSolati  thank you for looking into this and sorry for late response. I am travelling and I will not be able to come back to this for next couple of weeks. Feel free to close this if you need to. I will validate this once again anyway, but not sure when will I have a chance...
