### ISSUE TITLE
When to expect Firebase 7 support?

### ISSUE THREAD

**Issue by artaskerov** [geofirestore/geofirestore-js#155]
The current dependency is "firebase": "5.x.x || 6.x.x" even though Firebase 7 was released on September 26, 2019

**Comment by MichaelSolati** [comment]
The library does support Firebase 7 from my tests as there are no breaking changes. However the library doesn't really use firebase (it only uses it for typing), I could/should make an update to the package version.

**Comment by artaskerov** [comment]
> I could/should make an update to the package version.
That would be great, since it prevents the Firebase library in my project from updating to v7. Thank you, Michael!

**Comment by georgeMorales** [comment]
I've been with firebase 7 for a while and I haven't had any problems

**Comment by artaskerov** [comment]
Good to know. Thanks, @georgeMorales!

**Comment by MichaelSolati** [comment]
Version 3.4.0 is [running through travis now](https://travis-ci.org/geofirestore/geofirestore-js/builds/637738977) and should hopefully resolve this issue. Feel free to give it a shot!
