### ISSUE TITLE
ERROR in node_modules/geofirestore/dist/GeoDocumentSnapshot.d.ts:18:9 - error TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by THEDOWNCOUNTRY** [geofirestore/geofirestore-js#156]
I get an error every time I try to build this package in IONIC 4 app.

ERROR in node_modules/geofirestore/dist/GeoDocumentSnapshot.d.ts:18:9 - error TS1086: An accessor cannot be declared in an ambient context.

18     get native(): GeoFirestoreTypes.cloud.DocumentSnapshot | GeoFirestoreTypes.web.DocumentSnapshot;
           ~~~~~~
node_modules/geofirestore/dist/GeoDocumentSnapshot.d.ts:20:9 - error TS1086: An accessor cannot be declared in an ambient context.

20     get exists(): boolean;
           ~~~~~~
node_modules/geofirestore/dist/GeoDocumentSnapshot.d.ts:24:9 - error TS1086: An accessor cannot be declared in an ambient context.

24     get id(): string;
           ~~
node_modules/geofirestore/dist/GeoDocumentSnapshot.d.ts:26:9 - error TS1086: An accessor cannot be declared in an ambient context.

26     get ref(): GeoDocumentReference;
           ~~~
node_modules/geofirestore/dist/GeoWriteBatch.d.ts:19:9 - error TS1086: An accessor cannot be declared in an ambient context.

19     get native(): GeoFirestoreTypes.cloud.WriteBatch | GeoFirestoreTypes.web.WriteBatch;
           ~~~~~~
node_modules/geofirestore/dist/GeoFirestore.d.ts:14:9 - error TS1086: An accessor cannot be declared in an ambient context.

14     get native(): GeoFirestoreTypes.cloud.Firestore | GeoFirestoreTypes.web.Firestore;
           ~~~~~~
node_modules/geofirestore/dist/GeoDocumentReference.d.ts:18:9 - error TS1086: An accessor cannot be declared in an ambient context.

18     get native(): GeoFirestoreTypes.cloud.DocumentReference | GeoFirestoreTypes.web.DocumentReference;
           ~~~~~~
node_modules/geofirestore/dist/GeoDocumentReference.d.ts:20:9 - error TS1086: An accessor cannot be declared in an ambient context.

20     get id(): string;
           ~~
node_modules/geofirestore/dist/GeoDocumentReference.d.ts:24:9 - error TS1086: An accessor cannot be declared in an ambient context.

24     get firestore(): GeoFirestore;
           ~~~~~~~~~
node_modules/geofirestore/dist/GeoDocumentReference.d.ts:32:9 - error TS1086: An accessor cannot be declared in an ambient context.

32     get onSnapshot(): ((onNext: (snapshot: GeoDocumentSnapshot) => void, onError?: (error: Error) => void) => () => void);
           ~~~~~~~~~~
node_modules/geofirestore/dist/GeoDocumentReference.d.ts:36:9 - error TS1086: An accessor cannot be declared in an ambient context.

36     get parent(): GeoCollectionReference;
           ~~~~~~
node_modules/geofirestore/dist/GeoDocumentReference.d.ts:40:9 - error TS1086: An accessor cannot be declared in an ambient context.

40     get path(): string;
           ~~~~
node_modules/geofirestore/dist/GeoQuerySnapshot.d.ts:19:9 - error TS1086: An accessor cannot be declared in an ambient context.

19     get native(): GeoFirestoreTypes.cloud.QuerySnapshot | GeoFirestoreTypes.web.QuerySnapshot;
           ~~~~~~
node_modules/geofirestore/dist/GeoQuerySnapshot.d.ts:21:9 - error TS1086: An accessor cannot be declared in an ambient context.

21     get docs(): GeoFirestoreTypes.QueryDocumentSnapshot[];
           ~~~~
node_modules/geofirestore/dist/GeoQuerySnapshot.d.ts:23:9 - error TS1086: An accessor cannot be declared in an ambient context.

23     get size(): number;
           ~~~~
node_modules/geofirestore/dist/GeoQuerySnapshot.d.ts:25:9 - error TS1086: An accessor cannot be declared in an ambient context.

25     get empty(): boolean;
           ~~~~~
node_modules/geofirestore/dist/GeoQuery.d.ts:20:9 - error TS1086: An accessor cannot be declared in an ambient context.

20     get native(): GeoFirestoreTypes.cloud.Query | GeoFirestoreTypes.web.Query;
           ~~~~~~
node_modules/geofirestore/dist/GeoQuery.d.ts:24:9 - error TS1086: An accessor cannot be declared in an ambient context.

24     get firestore(): GeoFirestore;
           ~~~~~~~~~
node_modules/geofirestore/dist/GeoQuery.d.ts:33:9 - error TS1086: An accessor cannot be declared in an ambient context.

33     get onSnapshot(): ((onNext: (snapshot: GeoQuerySnapshot) => void, onError?: (error: Error) => void) => () => void);
           ~~~~~~~~~~
node_modules/geofirestore/dist/GeoQuery.d.ts:88:17 - error TS1086: An accessor cannot be declared in an ambient context.

88     private get _queryCriteria();
                   ~~~~~~~~~~~~~~
node_modules/geofirestore/dist/GeoCollectionReference.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.

15     get native(): GeoFirestoreTypes.cloud.CollectionReference | GeoFirestoreTypes.web.CollectionReference;
           ~~~~~~
node_modules/geofirestore/dist/GeoCollectionReference.d.ts:17:9 - error TS1086: An accessor cannot be declared in an ambient context.

17     get id(): string;
           ~~
node_modules/geofirestore/dist/GeoCollectionReference.d.ts:21:9 - error TS1086: An accessor cannot be declared in an ambient context.

21     get parent(): GeoDocumentReference | null;
           ~~~~~~
node_modules/geofirestore/dist/GeoCollectionReference.d.ts:26:9 - error TS1086: An accessor cannot be declared in an ambient context.

26     get path(): string;
           ~~~~
node_modules/geofirestore/dist/GeoTransaction.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.

15     get native(): GeoFirestoreTypes.cloud.Transaction | GeoFirestoreTypes.web.Transaction;
           ~~~~~~

[ERROR] An error occurred while running subprocess ng.
        
        ng run app:ionic-cordova-build:production --platform=ios exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.

**Comment by MichaelSolati** [comment]
Could you share your `tsconfig.json`?
