### ISSUE TITLE
Why do you have different document structure for  android IOS  and node js plugin.

### ISSUE THREAD

**Issue by raj860444** [geofirestore/geofirestore-js#157]
Why do you have different document structure for  android IOS  and node js plugin.

I can not find any data with condition which is inserted through android sdk. When putting where condition its ask me to create index .Its not working on my custom created index.If I am using link given by plugin to create index its create path for field with d.online.But my key putted directly in document.How I will access my records is there any way where I can override your conditions in node js project.

Please reply asap I appreciate your response thank you.

**Comment by MichaelSolati** [comment]
This library doesn't do android/iOS it does Node and Web (the official JS libraries). I am aware that the people who make react native firebase (not an official library, but a community maintained one) does a different structure than the JS libraries... Are you talking about the RNF library?

(I do believe this library works with RNF, but I do not support it per se...)

**Comment by leonamjlpaula** [comment]
Hi. Is possible to use this lib with React Native?

**Comment by MichaelSolati** [comment]
Yes, it works with RNF. While RNF isn't officially supported I try to fix issues people raise and it seems to work fine.
