### ISSUE TITLE
How to use Utils ? 

### ISSUE THREAD

**Issue by ashish-choudhary-appnweb** [geofirestore/geofirestore-js#158]
I am trying to use calculateDistance method from utils but i am not sure how should i access it as there is no documentation on that. If you could help me that would be really appreciable.

**Comment by MichaelSolati** [comment]
The functions in the `util` file are not exported/shared for public consumption. If you want I maintain a package called `geokit` which would provide what you're liking. [Here's the link](https://www.npmjs.com/package/geokit).
