### ISSUE TITLE
how to get the actual document from the d property?

### ISSUE THREAD

**Issue by Hishmad** [geofirestore/geofirestore-js#163]
Hi,

This is value.docs  object returned from the GeoQuerySnapshot

[{exists: true, id: "muRVtvwAKCORZYMlmdHW", distance: 0.7354152225474028, data: ƒ}]

how to get the document nested in d?

Kindly advice, thank you.

**Comment by MichaelSolati** [comment]
As you'd find in a standard firestore query, the data of your doc is located in the data field (which is a function). So call data like: `value.docs[0].data()`.

**Comment by technbuzz** [comment]
I am curious, why we need extra function to unfold the data?
