### ISSUE TITLE
How to use this with firebase v6 ?

### ISSUE THREAD

**Issue by bumjoo** [geofirestore/geofirestore-js#164]
Hi all.

I'm using firebase v6.3.1.
But, There's some issue to create GeoFirestore, I think.

```
(alias) const firestore: ReactNativeFirebase.FirebaseModuleWithStaticsAndApp
<FirebaseFirestoreTypes.Module, FirebaseFirestoreTypes.Statics>
import firestore

Argument of type 'FirebaseModuleWithStaticsAndApp<Module, Statics>' 
is not assignable to parameter of type 'Firestore | Firestore'.
  Type 'FirebaseModuleWithStaticsAndApp<Module, Statics>' is missing 
the following properties from type 'Firestore': settings, collection, doc, collectionGroup, 
and 5 more.ts(2345)

```
This error is occured to below code.
`
const geofirestore: GeoFirestore = new GeoFirestore(firestore);
`

How can I fix it ?

**Comment by MichaelSolati** [comment]
The firestore instance created by `ReactNativeFirebase` isn't the same object as what's returned by the `firebase` of `firebase-admin`, so the easiest thing is to cast the React Native firestore object to a type of `any`:

```typescript
const geofirestore: GeoFirestore = new GeoFirestore(firestore as any);
```

Let me know if that helps. (Keep in mind this library doesn't technically support `ReactNativeFirebase` as it's data structures can end up being different than the libraries from the Firebase team.)

**Comment by bumjoo** [comment]
Thank you so much for your answer. 
But, the code you show me doesn't work.

Here is the error message.
`Error: Firestore must be an instance of Firestore`

Is there any other way to fix it ?

(I understood that this library isn't technically supported)

**Comment by MichaelSolati** [comment]
It also looks like firestore is a function... Do you call it? (see below)

```Typescript
import firebase from 'react-native-firebase';
import { GeoFirestore } from 'geofirestore';

const firestore = firebase.firestore();
const geofirestore = new GeoFirestore(firestore as any);
```
