### ISSUE TITLE
 Invalid query. You have a where filter with an inequality (<, <=, >, or >=) on field 'd'

### ISSUE THREAD

**Issue by BadMask121** [geofirestore/geofirestore-js#170]
im trying aggregation query on the `d` field but i get this error `Error: firebase.firestore().collection().orderBy() Invalid query. You have a where filter with an inequality (<, <=, >, or >=) on field 'd.data' and so you must also use 'd.data' as your first Query.orderBy(), but your first Query.orderBy() is on field 'g' instead`

**Comment by MichaelSolati** [comment]
This unfortunately will not work, please read the [README.md](https://github.com/geofirestore/geofirestore-js#limitations--considerations)
