### ISSUE TITLE
Is it possible to use promises instead of event listeners

### ISSUE THREAD

**Issue by uslperera** [geofirestore/geofirestore-js#47]
According to this example code, you can perform the geo location based search.
```
const onKeyEnteredRegistration = geoQuery.on('key_entered', function(key, document, distance) {
  console.log(key + ' entered query at ' + document.coordinates.latitude + ',' + document.coordinates.longitude + ' (' + distance + ' km from center)');
});
```
Is it possible to use promises to get the same result. If so could you please give an example?

**Comment by MichaelSolati** [comment]
Unfortunately no, the library is designed to listen for changes in the database as well as your query and fire off new results as individual items as they come in. (Just how geofire does) In effect the query would never have a resolution (which a Promise would need) as it is always listening and updating.

You could instead use the `ready` listener to kill the subscription to your query when it triggers for now. However v3 will be more like the regular Firestore library where there will be promises and listeners.

**Comment by MichaelSolati** [comment]
@uslperera version 3.0.0 has a `get()` function which returns a promise. While v3 is massively different, the `spittin-hot-geofirestore` repo shows an example of how to use it promises with the library!

[Here you go](https://github.com/geofirestore/spittin-hot-geofirestore/blob/6a9c3482f8437f594c78743eb4fd96aee777a63b/src/app/services/restaurants.service.ts#L30)
