### ISSUE TITLE
Cannot initiate GeoFirestore instance in node.js application

### ISSUE THREAD

**Issue by AtakanCavuslu** [geofirestore/geofirestore-js#58]
I use GeoFirestore in my node.js application. In the first lines of the document i have:
`var GeoFirestore = require("geofirestore");`

And then i use the code 
`const geoFirestore = new GeoFirestore(collectionRef);`
With the collectionRef being a valid ref to the my firestore collection.

The issue is that i get the error "TypeError: GeoFirestore is not a constructor"
What is the problem here? Thanks for any help.

**Comment by MichaelSolati** [comment]
The `index.js` of geofirestore exports a few different files, so I can say your import wouldn't work. I believe you would want to do this (if you're not using Typescript or an ES6+):

```
var GeoFirestore = require("geofirestore").GeoFirestore;
```

Let me know if that works for you.

**Comment by AtakanCavuslu** [comment]
Yeah, it works now. That was the issue. Thanks!

**Comment by stot3** [comment]
So what would you use if you are using Angular, Typescript and this does not work like,

import {Geofirestore} from 'geofirestore';
