### ISSUE TITLE
Cannot read property '_currentGeohashesQueried' of undefined

### ISSUE THREAD

**Issue by felixchan** [geofirestore/geofirestore-js#61]
When I am updating the criteria for the query, oftentimes I get this error thrown. I have tried to put a try/catch block around updateCriteria, but this error still happens. Perhaps I am updating too quickly, and I should throttle it?

Is there a way to check if the query is currently updating, and if so, do not update?

![img_24616d0c75aa-1](https://user-images.githubusercontent.com/306524/50380697-68a22180-0635-11e9-8466-6bde710eeba1.jpeg)

**Comment by MichaelSolati** [comment]
Are you by chance using the react native firebase library?

**Comment by felixchan** [comment]
@MichaelSolati  Yes, RNFirebase :)

**Comment by MichaelSolati** [comment]
RNFirebase isn't officially supported. I believe it's worked for most, but the library is designed only for the official JS and Node Firebase libraries.

I would be open to adding support, in the future, but that is not currently a high priority.

**Comment by MichaelSolati** [comment]
(I do believe the issue does come from the behavior of set interval in diff JS environments. I'd suggest throttling back how often you update the location. It checks every second, so maybe try not to make a multiple changes in a second)

**Comment by MvRemmerden** [comment]
Any chance to make this faster? I'm trying to get the 15 closest documents, and depending on the location the radius they are in might be somewhere between 100 metres to 10 kilometres. So I decided to run a query for 100 meters, and then constantly increase the size until it has found 10 documents.

**Comment by MichaelSolati** [comment]
@mvremmerden I unfortunately can't think of a good way to do this, as it'd be an awkward expanding circle of queries. I am interested in adding `limit` support for 3.1.x, but that's the best I have planned.

**Comment by MichaelSolati** [comment]
@felixchan timers may not be necessary, but they allow for a clean and effective management of handling all active queries. I'd be down for a better solution, however it's not used in v3

**Comment by MvRemmerden** [comment]
@felixchan Interesting idea, will check out that technique as well. Thanks!
