### ISSUE TITLE
Bad implementation

### ISSUE THREAD

**Issue by alexandregiordanelli** [geofirestore/geofirestore-js#63]
There is not filter when query on firestore. In this project, you are getting all documents of collection and filter on client side. It is a big problem, because firestore has filters like .where and firebase realtime not. 

https://www.youtube.com/watch?v=mx1mMdHBi5Q

The engineer of firebase/google recommends this code:
https://jsbin.com/mosiza/edit?js,output

This solutions is scalable..

**Comment by alexandregiordanelli** [comment]
Sorry man! I didnt see the startAt and endAt filter.. I think you are right. I edited my issue and remove bad words.. Really sorry.. It is sad firestore doesnt have native geoqueries. thanks for share yor thoughts

**Comment by MichaelSolati** [comment]
Thank you for the apology @alexandregiordanelli , and I'm sorry if I came off a little strong. Anyway, I took your suggestion of using the `where` instead of my `startAt` and `endAt`. While I may not be able to do more with it now, I think it's the right solution for the library down the road.
