### ISSUE TITLE
geofirestore-js 3.0.0

### ISSUE THREAD

**Issue by Synercio** [geofirestore/geofirestore-js#68]
Hello team,

First of all, thanks for this great job :)

I've seen the tag 2.4.0 allow to add a custom query with the QueryCriteria but I didn't find it on the tag 3.0.0.

My goal is to limit the result from a firebase functions.

`const query: GeoQuery = geoFirestore.collection("elements").near({ center: location, radius: radius, query ??? });`

May you help me ?

(Sorry for my english)

**Comment by MichaelSolati** [comment]
Hey @Synercio, so this is not a problem at all. So `geofirestore` version 3 follows syntax much more similar to the regular firestore library. So instead you'd do this:

```
const query: GeoQuery = geoFirestore.collection('elements')
    .near({ center: location, radius: radius })
    .where('something', '==', 'something');
```

And you can keep on chaining `where` functions from there!

**Comment by Synercio** [comment]
Oh ok thanks :)

And for the "orderBy" and "limit" it's the same behaviour ?

**Comment by MichaelSolati** [comment]
`orderBy` and `limit` aren't supported in version 2 (you could do it, but it wouldn't work) or 3. However I'm looking to add both in later versions of 3.

**Comment by Synercio** [comment]
Ok, many thanks for your work @MichaelSolati :)

**Comment by MichaelSolati** [comment]
@alcuinguest so the problem with these additional sorts of filters for the queries stems from the fact that we aggregate multiple queries when you do a Geoquery.

Is the wage you hashes work is that we create an array of queries with geohashes that's around the area that you selected. So I could apply the order by or the limit to each of those queries, but when aggregated all those selections that you make will be lost. So then on the client side I have to reapply those selections. It's very much doable, it is not very much of efficient.

So it is something I'm very much looking into, but I will be taking probably a small break from this. I'm currently exploring with @thatadamedwards how we could make a sister library for Android developers.
