### ISSUE TITLE
Radius in meter or kilometers ?

### ISSUE THREAD

**Issue by Synercio** [geofirestore/geofirestore-js#69]
Hello hello, it's me again :-D

In the documentation, i read that radius value is in meter, however after some tests it's seems to be in kilometers, can you confirm that ?

Thanks team :)

**Comment by MichaelSolati** [comment]
It's in kilometers! That's a typo on my end. I'll fix that in a sec.

**Comment by Synercio** [comment]
Thanks @MichaelSolati 👍

**Comment by itwasmattgregg** [comment]
Don't think this was ever updated in the documentation. Can you please add this in the main README?

**Comment by MichaelSolati** [comment]
@itwasmattgregg don't worry, it's there I promise 😅

[In the README](https://github.com/geofirestore/geofirestore-js/commit/55fd7bd39c6276c069d4c22bb12d819299e81b54)

I haven't put comments/docs into interfaces yet, so that may be a necessary change up (and I'm open to PRs for that)

**Comment by markoddi** [comment]
Can we have miles? @MichaelSolati

**Comment by MichaelSolati** [comment]
@markoddi I don't have plans on doing that, at this time, however I'm option to people submitting pull requests to implement this as a feature.
