### ISSUE TITLE
Search by Road Distance

### ISSUE THREAD

**Issue by rajeshgadepalli** [geofirestore/geofirestore-js#74]
Is it possible in geofirestore to get results by the road distance ? 

Right now, when the center and radius are provided, geofirestore returns all points located within the radius basing on the straight line distance.

If i provide the center and the road distance, would like to get all points within that distance. 

Regards, 
Rajesh

**Comment by itwasmattgregg** [comment]
You would probably have to hook into a google maps api or similar to get that kind of information. Direct line will get you close right? Then you could filter further on the client.

**Comment by MichaelSolati** [comment]
@rajeshgadepalli this is very much above the scope or this project. You'd probably want to look into bounding boxes, so you would pass in a polyline, get the bounding boxes and then check if the point exists in the bounding boxes.
