### ISSUE TITLE
3.0.* - Readme suggestion/addition : (limit, startAt)

### ISSUE THREAD

**Issue by spoxies** [geofirestore/geofirestore-js#75]
Version 3 is such a seamless addition to Firestore that one would almost forget it is actually a 'workaround'. So a big thanks and compliments 🎉 !

With right the Readme reflects this seamless addition:

> The only difference being is the added ability... near()

> It effectively provides all the same functionality as the Firestore library..

Unless you are familiar with the workaround, and try or have a look under the hood, one would indeed optimistically assume that functions like .limit() .orderBy() .startAt() .startAfter() would work as other queries. 

Maybe the sooner a developer is aware of a limitation, the better. For example it could structure the database (strategy) on beforehand to deal with this.

Anyway no complains here, just admiration and a lot of thanks!

**Comment by MichaelSolati** [comment]
@spoxies I appreciate the `README.md` update! Unfortunately it's not an easy problem to solve, I have a solution in mind but it is not efficient. I got a bunch of features everyone wants that I need to get in 😅

**Comment by spoxies** [comment]
@MichaelSolati I totally understand! Given the existing limits of GCFS 3.0 is by far the best solution possible. 

A implementation of the methods above, would most likely be a client side thing anyway. IMHO not having the methods makes it transparent and prevents confusion or complaints about 'data/query usage'. 

Thanks for approving the PR! ❤️ 

p.s. If anyone else is reading this and looking for a lazy way to sort(), limit(), skip(): https://www.npmjs.com/package/faltu
