### ISSUE TITLE
3.0.*- where() inequality filter on multiple properties

### ISSUE THREAD

**Issue by spoxies** [geofirestore/geofirestore-js#78]
Having multiple 'inequality filters' on multiple properties isn't possible in Cloud Firestore. Therefore doing a query like bellow is not possible because GeoFirestore already does a filter on `g`.
```
geoInvites.near({'center': coordinates, 'radius': radius})
.where('date', '>=', new Date())
```
Prior to a certain issue I just happen to see and will not mention, GeoQuery.ts used `startAt()` internally. Thus allowing 'normal' `where()` queries.

Personally I use `where()` much more commonly/naturally. And if I'm correct the `.near()` interface currently does not allow for chaining `.sort()` and  `.startAt` to solve this particular example/problem. 

Could I purpose and would it make sense to revert src/GeoQuery.ts - 7beffe691588fa9db871cde3e95554624e141230 ?

**Comment by spoxies** [comment]
I did not realise that the change from `where()` to `startAt()` wasn't the solution for this example problem. So I like to apologise, because it is not a "Fix". Unfortunately this did not became apparent from the mocha tests.

Only when implementing it as an actual (cloud) function:

**Example**:
`geoInvites.near({'center': coordinates, 'radius': radius}).where('date', '>=', new Date())`

**Output**:
`inequality filter property and first sort order must be the same: d.date and g`

**Comment by MichaelSolati** [comment]
@spoxies darn, well this is something I'll have to explore still. I'll probably accept your PR and go from there (thank you)

**Comment by MichaelSolati** [comment]
So I've been doing some looking/tinkering/research an I don't think that this problem will be fixed. Because we have to do ordering on the `g` field we can't do ordering on other fields (no `<`, `>`, `<=`, `>=`) => [see the Firestore docs](https://firebase.google.com/docs/firestore/query-data/queries#compound_queries)

**Comment by luklew** [comment]
@MichaelSolati do you know what would be a good work around? I need to grab documents nearby based on a few criteria that require '>' and '<' but not sure what would be the best approach.

**Comment by MichaelSolati** [comment]
@luklew the filter withe geolocation and the added `<` or `>` would need to take place on client. You could do this on a cloud function if you didn't want to handle compute in the browser, but those are kinda your only options.

**Comment by luklew** [comment]
@MichaelSolati thanks for the answer, when you say on the client, does that mean basically get the nearest documents using .near(), then once the documents have been downloaded run them through a loop and do the filtering there?

**Comment by MichaelSolati** [comment]
@luklew yes... Probably not what you wanted, but it's the best that I can think of.

**Comment by ofriavieli** [comment]
@MichaelSolati  Is it possible with Geofirestore to use the "orderBy" method for a different field (not the geopoint)?  I know it is probably not possible when using the "near()" method, but is it possible without it?
