### ISSUE TITLE
How do we store data?

### ISSUE THREAD

**Issue by voidstarfire** [geofirestore/geofirestore-js#81]
Am I missing something big here, I looked at the docs and there's nothing.

How are we suppose to store data with Firestore using this lib exactly?

**Comment by MichaelSolati** [comment]
So the library expects you to use `geofirestore` to add data. However if you choose not to there are a few things that are expected...

- The top level of the doc had 3 fields. `g`, a geohash string in lowercase, `l` a geopoint, and `d` the data you want to store.
- When you add a document to a collection, `collectionRef.add({ coordinates: new Firebase.firestore.GeoPoint(0, 0) })`, the function looks for a field called coordinates (I'm answering on my phone, can't check, but pretty positive) to create a geohash from. However you can pass in a string as a second argument to tell `geofirestore` what field to use for the location.
- There is a [code sample](https://github.com/geofirestore/spittin-hot-geofirestore/blob/6a9c3482f8437f594c78743eb4fd96aee777a63b/data/src/utils.ts#L19) on how to mass add data to a collection in the proper format without using `geofirestore` that you may like.

**Comment by voidstarfire** [comment]
Ok thanks there's no mention of this anywhere in any of the docs.

**Comment by voidstarfire** [comment]
Ah it's not so friendly for other developers who might just open it and wonder why there are single char vars.

Anyhow. I cannot find any cloud functions documentation anywhere for storing the data, can you point me in the right direction? Thanks for the replies.

**Comment by MichaelSolati** [comment]
I can throw together a little sample, is there something in specific you're looking to do?

**Comment by voidstarfire** [comment]
That would be awesome man.

**Comment by MichaelSolati** [comment]
@voidstarfire I was super busy this past week, but [here is a little sample](https://gist.github.com/MichaelSolati/4de01bd32c726c4f81e21bddc30edca2)

**Comment by voidstarfire** [comment]
Thanks so much you're great! Would be nice if this was in the docs :-)

Just a question, does this modify all the existing data at any point in the future? I have millions of users I'm playing with here so I gotta be super careful (Of course this is executed on backup dev databases when we test but sometimes you never know with libraries.)

**Comment by MichaelSolati** [comment]
That sample does not modify existing data, only new. You can do something similar with a geofirestore batch id say. It could be interesting to write (but totally doable)

I'm currently focused on writing tests for `runTransactions`. But before launching that with v3.2.0 I'll update the readme

**Comment by voidstarfire** [comment]
Do you mean that new data is created in a GeoFire format or do mean that existing data can be created into new GeoFire data losing the fields or not? 😅

I'll try running a batch on the database, will cost me a $$$ 😂

**Comment by MichaelSolati** [comment]
Batch should save you some $$$ as it'll allow you to modify up to 500 docs in one write. (Instead of individual writes). And I'm not sure if I understand your question, but the code snippet was to take a non geofirestore doc and turn it into one without losing the data fields (just embed it into the geodoc)

**Comment by voidstarfire** [comment]
Thanks for your replies man.

I tried to implement your example but it's not working at all.

I have existing users with 'geopoint' field and I can't seem to update those docs into geofireones (There's no documentation anywhere on that, how do we convert docs into geofirestore ones?, this is all I can find: https://geofirestore.com/#documentation almost nothing.)

**Comment by voidstarfire** [comment]
I'm not sure if I'm doing this wrong. I saw your example. There's no docs on updating existing documents.

Trying update one doc which has an existing lat, long object as 'geoPoint'
```
await functions.firestore
    .document('users/{S1NT5Sti5pO3qpW47wmYGHDFTv93}')
    .onCreate((snap: FirebaseFirestore.DocumentSnapshot) => {
        const collection = new GeoFirestore(firestore()).collection('users');
        return collection.doc(snap.id).update(snap.data(), 'geoPoint')
    });
```

**Comment by voidstarfire** [comment]
I got it working but randomly the 'd' field doesn't update. 

Is it possible to skip using the 'd' field and just use the document data? (Which will be the case almost 100% of the time anyhow). There are almost no docs for this library.

Would be nice to run it off just g (geohash) and l (location)?

**Comment by MichaelSolati** [comment]
So unfortunately the `d` field is necessary for abstraction and preventing data from being corrupted. Wanna post a snippet/example of how things look for you (some code, some screenshots, hopefully I'd be able to help)

**Comment by voidstarfire** [comment]
The data would be corrupted in a read only scenarioDictionary? Using 'near' for example?

**Comment by MichaelSolati** [comment]
I'm sorry I'm uncertain of what you mean. Uhm, ideally we wrap all the docs so you never need to worry about the sub document `d`.

Anyway, what I think you're talking about is using the `update` function, which requires a flat document. If you need to update sub documents [you'd need to use dot notation](https://geofirestore.com/classes/_geowritebatch_.geowritebatch.html#update) to target those fields (similar to how firestore does update). If that would be an issue, I'd advise you to use the `set` function.

**Comment by voidstarfire** [comment]
Thanks so much for your help dude. It was was solved by just putting everything in a special 'geofireUsers' collection.

 I use set here all the time.

It's working really really fast now. I mean like how.. lol..
