### ISSUE TITLE
Feature Request / Issue: No Pagination using geofirestore - how do I get around this?

### ISSUE THREAD

**Issue by markoddi** [geofirestore/geofirestore-js#86]
When will you be adding pagination to this geofirestore?

I'm also open to other options for pagination.

Currently I use limit and increment that by 20 each time but its not really good enough especially since it calls bigger payloads each time and then orders them again as the list grows in ascending.

I've made a stackoverflow: https://stackoverflow.com/questions/54673938/im-using-geofirestore-with-firestore-and-want-to-paginate-the-results

**If pagination is not available, questions:**

1. When will it be?
2. How can I get around this for now?
3. If its available how do I do it, normally I use startAt etc?

**Comment by MichaelSolati** [comment]
So the limit function on `geofirestore` ends up [sorting the results in order of their distance](https://github.com/geofirestore/geofirestore-js/blob/v3.2.1/src/GeoJoinerOnSnapshot.ts#L59) and cuts off results that are larger than the limit while keeping only the closest document. 

Geoqueries require an aggregation of queries, so geofirestore scans geohashes around the coords you input. That way if you're point is by the borderline of where a hash could be we don't miss areas right outside of that hash. We have to query more docs to make sure we get the ones near your point.

**Comment by jerryheir** [comment]
I really dont understand this. Especially when trying to scale or minimize costs. If I make a query with limit to 20, that is 20 reads. If I want to continue and I make a read with limit of 40 reads ... That is a total of 60 reads. This way does more damage than solution : (
