### ISSUE TITLE
Support for nested properties setting customKey in collection.add() method?

### ISSUE THREAD

**Issue by paolospag** [geofirestore/geofirestore-js#88]
Hi,
I'm using this awesome library to perform nearby query, but I noticed a limit when call `add()` method  providing `customKey` param: I'm not able to set nested properties of data object, i.e. `place.coordinates`, and looking at the code I found this limit in `utils.ts`: https://github.com/geofirestore/geofirestore-js/blob/master/src/utils.ts#L295

My question: is it possible to add support for nested properties? I would like to do something like that:
```jsx
const geofirestore = new GeoFirestore(firebase.firestore());
const geocollection = geofirestore.collection('availabilities');
export const createGeoData = (data) => geocollection.add(data, 'place.coordinates');
```

Probably this isn't a bug issue or something like that, but it could be an enhancement.

**Comment by paolospag** [comment]
@MichaelSolati any update on this?

**Comment by MichaelSolati** [comment]
I have a plan on place but I just haven't had time to get to this. I should have something by the end of the month though

**Comment by paolospag** [comment]
@MichaelSolati I need this feature as soon as possible, when do you think it will be available?

**Comment by MichaelSolati** [comment]
@paolospag So I think this will work, it required more work then I thought and as I have been traveling I haven't had the time to fix it.

```
npm i geofirestore/geofirestore-js#feat/findCoordinates
```

If it works I'll deploy it to NPM.

**Comment by paolospag** [comment]
@MichaelSolati Sorry for my late response. Thank you for the stuff, I'll take a look tomorrow and I'll let you know.

**Comment by paolospag** [comment]
@MichaelSolati I confirm that it now works exactly as I expected, thanks a lot!

Please notify me on this issue when you deploy it to npm, then you can close this issue.
