### ISSUE TITLE
[Feature] Distance in the result

### ISSUE THREAD

**Issue by sedestrian** [geofirestore/geofirestore-js#90]
It would be really cool if the library gave you the option to get the distance of each result from the center

**Comment by MichaelSolati** [comment]
It does! When you make a query you get `QueryDocumentSnapshot`s back which have a distance field.


https://geofirestore.com/interfaces/_geofirestoretypes_.geofirestoretypes.querydocumentsnapshot.html

**Comment by sedestrian** [comment]
Oh wow amazing! I didn't realize
