### ISSUE TITLE
Inequality

### ISSUE THREAD

**Issue by teddyteh** [geofirestore/geofirestore-js#92]
I know this is related to https://github.com/geofirestore/geofirestore-js/issues/78 but is there no way around this? How would I achieve something similar?

```
this.queueRef
            .where('d.timeRequested', '>', moment().subtract(1, "days").toDate())
            .near({
                center: new firebase.firestore.GeoPoint(this.currentLocation.latitude, this.currentLocation.longitude),
                radius: 1 // km
            })
```

Thanks!

**Comment by MichaelSolati** [comment]
Unfortunately no, not at this time at least. There are unfortunately still some limitations to Firestore 😕
