### ISSUE TITLE
Distance helper function

### ISSUE THREAD

**Issue by uturnr** [geofirestore/geofirestore-js#94]
Great library! I used to use the distance helper function in 2.x, and I'm wondering if there's any way to access it in 3.x.

For me it was useful to display a user's distance from a location immediately after they added it.

**Comment by MichaelSolati** [comment]
I don't think this will fit in with the new format of geofirestore. However I do have a super lightwight library (geohelper) which would probably be perfect for you => https://github.com/MichaelSolati/geokit#geokitdistancestart-latlngliteral-end-latlngliteral-unit-string-number
